// src/services/Manager/FinalDefenseData.js
 
export const finalDefenseData = {
  // ================================
  // AGILE
  // ================================
  Agile: {
    phases: ["Develop", "Test", "Deploy", "Review"],
    taskTypes: {
      Develop: ["Documentation", "System Development", "Discussion & Review"],
      Test: ["Documentation", "System Development", "Discussion & Review"],
      Deploy: ["Documentation", "System Development", "Discussion & Review"],
      Review: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "1.Polish: Chapter 1",
        "2.Polish: Chapter 2",
        "5.Polish: Chapter 3",
        "4.Polish: Chapter 4",
        "9.Development",
        "6.Verification and Testing",
        "1.Implementation Plan",
        "2.Installation Process",
        "3.Complete: Chapter 5",
        "4.Finalize Supporting Sections",
        "5.Final Manuscript Revision (Post-Defense)",
        "6.Manuscript Submission",
        "Manuscript Submission for AI and Plagiarism Check",
      ],
      "System Development": [
        "1.UI Development",
        "2.Database Implementation",
        "3.Functionality Implementation",
        "4.Bug Fixing",
        "5.System QA",
        "6.Bug Fixing and Final Adjustments",
        "7.Deploy the System",
        "8.Gather Target Users/Client",
        "9.Review Users Feedback",
        "10.Gather Users/Client Feedback",
        "11.Update System Functionalities",
        "12.Final Defense",
        "13.Final Re-Defense Planning",
        "14.Final Defense Feedback Integration",
      ],
      "Discussion & Review": [
        "1.Capstone Meeting",
        "2.Adviser Consultation",
        "3.Meeting with the User/Client",
        "Final Defense Preparation",
      ],
    },
    subtasks: {
      "1.Polish: Chapter 1": ["4.Introduction", "5.Objectives", "6.Scope and Limitation"],
      "2.Polish: Chapter 2": ["3.Related Theories", "4.Related Literature"],
      "5.Polish: Chapter 3": ["5.Implementation", "6.Development"],
      "4.Polish: Chapter 4": ["5.Methodology", "6.Environment", "7.Requirement Specification", "8.Design"],
      "9.Development": [
        "1.Software",
        "2.Hardware Specification",
        "3.Program Specification",
        "4.Programming Enviroment",
        "5.Development Diagram",
        "6.Test Plan",
      ],
      "6.Verification and Testing": ["1.Unit Testing", "2.Integration Testing", "3.System Testing", "4.Acceptance Testing"],
      "1.Implementation Plan": ["1.Physical Environment", "2.Interfaces", "3.Functionality", "4.Data", "5.Security"],
      "3.Complete: Chapter 5": ["1.Conclusion", "2.Recomendations", "3.Appendices"],
      "4.Finalize Supporting Sections": ["1.References", "2.Resource Person", "4.Appendices"],
      "5.System QA": [
        "1.Unit Testing",
        "2.Compatibility Testing",
        "3.Performance Testing",
        "4.Stress Testing",
        "5.Load Testing",
        "6.Concurrent Testing",
        "7.Pacing Time",
        "8.Response Time",
        "9.Network Testing",
      ],
      "Final Defense Preparation": [
        "System Testing Request Letter",
        "1.PowerPoint Presentation",
        "2.Mock Defense",
        "3.Manuscript Printing",
      ],
    },
    elements: {
      "4.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "5.Objectives": ["General Objectives", "Specific Objectives"],
      "6.Scope and Limitation": ["Scope", "Limitation"],
      "5.Implementation": ["Hardware", "Software", "Peopleware"],
      "6.Development": ["Hardware", "Software", "Peopleware"],
      "6.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "7.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "8.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "4.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "6.Test Plan": ["Test Data"],
      "2.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "3.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "3.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "4.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
    },
  },
 
  // ================================
  // EXTREME PROGRAMMING (XP)
  // ================================
  "Extreme Programming": {
    phases: ["Coding", "Testing", "Listening"],
    taskTypes: {
      Coding: ["Documentation", "System Development", "Discussion & Review"],
      Testing: ["Documentation", "System Development", "Discussion & Review"],
      Listening: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "1.Polish: Chapter 1",
        "2.Polish: Chapter 2",
        "5.Polish: Chapter 3",
        "4.Polish: Chapter 4",
        "9.Development",
        "6.Verification and Testing",
        "1.Implementation Plan",
        "2.Installation Process",
        "3.Complete: Chapter 5",
        "4.Finalize Supporting Sections",
        "5.Final Manuscript Revision (Post-Defense)",
        "6.Manuscript Submission",
        "1.Manuscript Submission for AI and Plagiarism Check",
      ],
      "System Development": [
        "2.Development Environment Setup & Pair Assignment",
        "3.User Interface Coding with Customer Collaboration",
        "4.Incremental Database Development",
        "5.Test-Driven Feature Development",
        "6.Continuous Integration",
        "7.Bug Fixing",
      ],
      Testing: [
        "8.System QA",
        "6.Bug Fixing and Final Adjustments",
        "7.Deploy the System",
      ],
      Listening: [
        "8.Engage Customer & Stakeholders",
        "9.Collaborate on Feedback Review",
        "10.Conduct Iterative Requirement Gathering",
        "11.Refine Features Based on Customer Input",
        "12.Final Defense",
        "13.Final Re-Defense Planning",
        "14.Final Defense Feedback Integration",
      ],
      "Discussion & Review": [
        "1.Capstone Meeting",
        "2.Adviser Consultation",
        "3.Meeting with the User/Client",
        "Final Defense Preparation",
      ],
    },
    subtasks: {
      "1.Polish: Chapter 1": ["4.Introduction", "5.Objectives", "6.Scope and Limitation"],
      "2.Polish: Chapter 2": ["3.Related Theories", "4.Related Literature"],
      "5.Polish: Chapter 3": ["18.Implementation", "19.Development"],
      "4.Polish: Chapter 4": ["5.Methodology", "6.Environment", "7.Requirement Specification", "8.Design"],
      "9.Development": [
        "1.Software",
        "2.Hardware Specification",
        "3.Program Specification",
        "4.Programming Enviroment",
        "5.Development Diagram",
        "6.Test Plan",
      ],
      "6.Verification and Testing": ["1.Unit Testing", "2.Integration Testing", "3.System Testing", "4.Acceptance Testing"],
      "1.Implementation Plan": ["1.Physical Environment", "2.Interfaces", "3.Functionality", "4.Data", "5.Security"],
      "3.Complete: Chapter 5": ["1.Conclusion", "2.Recomendations", "3.Appendices"],
      "4.Finalize Supporting Sections": ["1.References", "2.Resource Person", "3.Appendices"],
      "8.System QA": [
        "1.Unit Testing",
        "2.Compatibility Testing",
        "3.Performance Testing",
        "4.Stress Testing",
        "5.Load Testing",
        "9.Concurrent Testing",
        "10.Pacing Time",
        "11.Response Time",
        "12.Network Testing",
      ],
      "Final Defense Preparation": [
        "System Testing Request Letter",
        "1.PowerPoint Presentation",
        "2.Mock Defense",
        "3.Manuscript Printing",
      ],
    },
    elements: {
      "4.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "5.Objectives": ["General Objectives", "Specific Objectives"],
      "6.Scope and Limitation": ["Scope", "Limitation"],
      "18.Implementation": ["Hardware", "Software", "Peopleware"],
      "19.Development": ["Hardware", "Software", "Peopleware"],
      "6.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "7.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "8.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "4.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "6.Test Plan": ["Test Data"],
      "2.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "3.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "3.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "4.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
    },
  },
 
  // ================================
  // SPIRAL
  // ================================
  Spiral: {
    phases: ["Engineering", "Evaluation"],
    taskTypes: {
      Engineering: ["Documentation", "System Development", "Discussion & Review"],
      Evaluation: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "1.Polish: Chapter 1",
        "2.Polish: Chapter 2",
        "3.Polish: Chapter 3",
        "4.Polish: Chapter 4",
        "5.Development",
        "6.Verification and Testing",
        "1.Implementation Plan",
        "2.Installation Process",
        "3.Complete: Chapter 5",
        "4.Finalize Supporting Sections",
        "5.Final Manuscript Revision (Post-Defense)",
        "6.Manuscript Submission",
        "Manuscript Submission for AI and Plagiarism Check",
      ],
      "System Development": [
        "1.User Interface Construction",
        "2.Database Design & Integration",
        "3.Feature Development & Integration",
        "4.System Debugging & Correction",
        "5.System QA",
        "6.Bug Fixing and Final Adjustments",
        "7.Deploy the System",
      ],
      "Discussion & Review": [
        "2.Capstone Meeting",
        "3.Adviser Consultation",
        "4.Meeting with the User/Client",
        "Final Defense Preparation",
      ],
    },
    subtasks: {
      "1.Polish: Chapter 1": ["1.Introduction", "2.Objectives", "3.Scope and Limitation"],
      "2.Polish: Chapter 2": ["1.Related Theories", "2.Related Literature"],
      "3.Polish: Chapter 3": ["1.Implementation", "2.Development"],
      "4.Polish: Chapter 4": ["1.Methodology", "2.Environment", "3.Requirement Specification", "4.Design"],
      "5.Development": [
        "1.Software",
        "2.Hardware Specification",
        "3.Program Specification",
        "4.Programming Enviroment",
        "5.Development Diagram",
        "6.Test Plan",
      ],
      "6.Verification and Testing": ["1.Unit Testing", "2.Integration Testing", "3.System Testing", "4.Acceptance Testing"],
      "1.Implementation Plan": ["1.Physical Environment", "2.Interfaces", "3.Functionality", "4.Data", "5.Security"],
      "3.Complete: Chapter 5": ["1.Conclusion", "2.Recomendations", "3.Appendices"],
      "4.Finalize Supporting Sections": ["1.References", "2.Resource Person", "4.Appendices"],
      "5.System QA": [
        "1.Unit Testing",
        "2.Compatibility Testing",
        "3.Performance Testing",
        "4.Stress Testing",
        "5.Load Testing",
        "6.Concurrent Testing",
        "7.Pacing Time",
        "8.Response Time",
        "9.Network Testing",
      ],
      "Final Defense Preparation": [
        "System Testing Request Letter",
        "1.PowerPoint Presentation",
        "2.Mock Defense",
        "3.Manuscript Printing",
      ],
    },
    elements: {
      "1.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "2.Objectives": ["General Objectives", "Specific Objectives"],
      "3.Scope and Limitation": ["Scope", "Limitation"],
      "1.Implementation": ["Hardware", "Software", "Peopleware"],
      "2.Development": ["Hardware", "Software", "Peopleware"],
      "2.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "3.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "4.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "4.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "6.Test Plan": ["Test Data"],
      "2.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "3.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "3.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "4.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
    },
  },
 
  // ================================
  // RAD
  // ================================
   RAD: {
    phases: ["Construction", "Cutover"],
    taskTypes: {
      Engineering: ["Documentation", "System Development", "Discussion & Review"],
      Evaluation: ["Documentation", "System Development", "Discussion & Review"],
    },
    tasks: {
      Documentation: [
        "1.Polish: Chapter 1",
        "2.Polish: Chapter 2",
        "3.Polish: Chapter 3",
        "4.Polish: Chapter 4",
        "5.Development",
        "6.Verification and Testing",
        "1.Implementation Plan",
        "2.Installation Process",
        "3.Complete: Chapter 5",
        "4.Finalize Supporting Sections",
        "5.Final Manuscript Revision (Post-Defense)",
        "6.Manuscript Submission",
        "Manuscript Submission for AI and Plagiarism Check",
      ],
      "System Development": [
        "1.User Interface Construction",
        "2.Database Implementation",
        "3.Functionality Implementation",
        "4.Conduct Iterative Internal Testing",
        "5.Bug Fixing",
        "6.System QA",
        "7.Apply Rapid Fixes Based on Test Results",
        "7.Bug Fixing and Final Adjustments",
      ],
      "Discussion & Review": [
        "2.Capstone Meeting",
        "3.Adviser Consultation",
        "4.Meeting with the User/Client",
        "Final Defense Preparation",
      ],
    },
    subtasks: {
      "1.Polish: Chapter 1": ["1.Introduction", "2.Objectives", "3.Scope and Limitation"],
      "2.Polish: Chapter 2": ["1.Related Theories", "2.Related Literature"],
      "3.Polish: Chapter 3": ["1.Implementation", "2.Development"],
      "4.Polish: Chapter 4": ["1.Methodology", "2.Environment", "3.Requirement Specification", "4.Design"],
      "5.Development": [
        "1.Software",
        "2.Hardware Specification",
        "3.Program Specification",
        "4.Programming Enviroment",
        "5.Development Diagram",
        "6.Test Plan",
      ],
      "6.Verification and Testing": ["1.Unit Testing", "2.Integration Testing", "3.System Testing", "4.Acceptance Testing"],
      "1.Implementation Plan": ["1.Physical Environment", "2.Interfaces", "3.Functionality", "4.Data", "5.Security"],
      "3.Complete: Chapter 5": ["1.Conclusion", "2.Recomendations", "3.Appendices"],
      "4.Finalize Supporting Sections": ["1.References", "2.Resource Person", "4.Appendices"],
      "5.System QA": [
        "1.Unit Testing",
        "2.Compatibility Testing",
        "3.Performance Testing",
        "4.Stress Testing",
        "5.Load Testing",
        "6.Concurrent Testing",
        "7.Pacing Time",
        "8.Response Time",
        "9.Network Testing",
      ],
      "Final Defense Preparation": [
        "System Testing Request Letter",
        "1.PowerPoint Presentation",
        "2.Mock Defense",
        "3.Manuscript Printing",
      ],
    },
    elements: {
      "1.Introduction": ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
      "2.Objectives": ["General Objectives", "Specific Objectives"],
      "3.Scope and Limitation": ["Scope", "Limitation"],
      "1.Implementation": ["Hardware", "Software", "Peopleware"],
      "2.Development": ["Hardware", "Software", "Peopleware"],
      "2.Environment": ["Locale", "Population of the Study", "Organizational Chart/Profile"],
      "3.Requirement Specification": [
        "Operational Feasibility [Fishbone Diagram]",
        "Operational Feasibility [Functional Decomposition Diagram]",
        "Technical Feasibility",
        "Schedule Feasibility",
        "Economic Feasibility",
        "Requirements Modeling [Context Diagram]",
        "Requirements Modeling [Data Flow Diagram]",
        "Requirements Modeling [System Flowchart]",
        "Requirements Modeling [Program Flowchart]",
        "Requirements Modeling [Use Case Diagram]",
        "Requirements Modeling [Use Class Diagram]",
        "Requirements Modeling [Sequence  Diagram]",
        "Requirements Modeling [Activity Diagram]",
        "Risk Assessment/Analysis",
      ],
      "4.Design": [
        "Output and User-interface Design Forms",
        "Data Design",
        "System Architecture [Network Model]",
        "System Architecture [Network Topology]",
        "System Architecture [Network Security]",
      ],
      "4.Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
      "6.Test Plan": ["Test Data"],
      "2.Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
      "3.System Testing": ["System Function", "Test Data", "Test Result and Observations"],
      "3.Appendices": ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
      "4.Appendices": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
    },
  },
 
 
  // ================================
  // PROTOTYPING
  // ================================
  Prototyping: {
  phases: ["Refining Prototype", "Implement Product & Maintain"],
  taskTypes: {
    "Refining Prototype": ["Documentation", "System Development", "Discussion & Review"],
    "Implement Product & Maintain": ["Documentation", "System Development", "Discussion & Review"],
    "Discussion & Review": ["Documentation", "System Development", "Discussion & Review"],
  },
  tasks: {
    Documentation: [
      "Refine UI & Functionalities based on Panel Feedback",
      "Polish: Chapter 1",
      "Polish: Chapter 2",
      "Polish: Chapter 3",
      "Polish: Chapter 4",
      "Development",
      "Verification and Testing",
      "Implementation Plan",
      "Installation Process",
      "Complete: Chapter 5",
      "Finalize Supporting Sections",
      "Final Manuscript Revision (Post-Defense)",
      "Manuscript Submission",
      "Manuscript Submission for AI and Plagiarism Check",
    ],
    "System Development": [
      "UI Development",
      "Database Implementation",
      "Implement Core Functional Modules",
      "Perform System Maintenance and Issue Resolution",
      "System QA",
      "Bug Fixing and Final Adjustments",
      "Deploy the System",
      "Conduct Post-Deployment User Feedback Review",
      "Review Users Feedback",
      "Update System Functionalities",
      "Final Defense",
      "Final Re-Defense Planning",
      "Final Defense Feedback Integration",
    ],
    "Discussion & Review": [
      "Capstone Meeting",
      "Adviser Consultation",
      "Meeting with the User/Client",
      "Final Defense Preparation",
    ],
  },
  subtasks: {
    "Polish: Chapter 1": ["Introduction", "Objectives", "Scope and Limitation"],
    "Polish: Chapter 2": ["Related Theories", "Related Literature"],
    "Polish: Chapter 3": ["Implementation", "Development"],
    "Polish: Chapter 4": ["Methodology", "Environment", "Requirement Specification", "Design"],
    Development: [
      "Software",
      "Hardware Specification",
      "Program Specification",
      "Programming Enviroment",
      "Development Diagram",
      "Test Plan",
    ],
    "Verification and Testing": ["Unit Testing", "Integration Testing", "System Testing", "Acceptance Testing"],
    "Implementation Plan": ["Physical Environment", "Interfaces", "Functionality", "Data", "Security"],
    "Complete: Chapter 5": ["Conclusion", "Recomendations", "Appendices"],
    "Finalize Supporting Sections": ["References", "Resource Person", "Appendices"],
    "System QA": [
      "Unit Testing",
      "Compatibility Testing",
      "Performance Testing",
      "Stress Testing",
      "Load Testing",
      "Concurrent Testing",
      "Pacing Time",
      "Response Time",
      "Network Testing",
    ],
    "Final Defense Preparation": [
      "System Testing Request Letter",
      "PowerPoint Presentation",
      "Mock Defense",
      "Manuscript Printing",
    ],
  },
  elements: {
    Introduction: ["Project Context", "Background of the Study", "Policies and Procedures", "Users Position"],
    Objectives: ["General Objectives", "Specific Objectives"],
    "Scope and Limitation": ["Scope", "Limitation"],
    Implementation: ["Hardware", "Software", "Peopleware"],
    Development: ["Hardware", "Software", "Peopleware"],
    Environment: ["Locale", "Population of the Study", "Organizational Chart/Profile"],
    "Requirement Specification": [
      "Operational Feasibility [Fishbone Diagram]",
      "Operational Feasibility [Functional Decomposition Diagram]",
      "Technical Feasibility",
      "Schedule Feasibility",
      "Economic Feasibility",
      "Requirements Modeling [Context Diagram]",
      "Requirements Modeling [Data Flow Diagram]",
      "Requirements Modeling [System Flowchart]",
      "Requirements Modeling [Program Flowchart]",
      "Requirements Modeling [Use Case Diagram]",
      "Requirements Modeling [Use Class Diagram]",
      "Requirements Modeling [Sequence  Diagram]",
      "Requirements Modeling [Activity Diagram]",
      "Risk Assessment/Analysis",
    ],
    Design: [
      "Output and User-interface Design Forms",
      "Data Design",
      "System Architecture [Network Model]",
      "System Architecture [Network Topology]",
      "System Architecture [Network Security]",
    ],
    "Programming Enviroment": ["Front End", "Back End", "Programming Considerations and Issues"],
    "Test Plan": ["Test Data"],
    "Integration Testing": ["Compatibility Testing", "Performance Testing", "Stress Testing", "Load Testing"],
    "System Testing": ["System Function", "Test Data", "Test Result and Observations"],
    Appendices: ["Appendix F", "Appendix G", "Appendix H", "Appendix I"],
    "Finalize Supporting Sections": ["Appendix A", "Appendix B", "Appendix C", "Appendix D", "Appendix E"],
  },
},
};