// ManagerTitleTaskData.js
// ==================
// Centralized data for Title Task Creation

export const methodologyList = ["Agile", "Extreme Programming", "RAD", "Prototyping", "Spiral"];

export const projectPhaseMap = {
  Agile: "Planning",
  "Extreme Programming": "Planning",
  RAD: "Requirements",
  Prototyping: "Requirements and Gathering Analysis",
  Spiral: "Plan",
};

export const taskTypeList = ["Documentation", "Discussion & Review"];

// ================== Documentation Tasks ==================
export const documentationTasks = {
  Agile: [
    "Brainstorming",
    "Data Gathering: Internet Research",
    "Title Proposal: Concepts and Layouts",
    "Interview User/Client",
    "Collect User/Client Requirements",
    "Title Proposal: Selection of Three Titles",
    "Refining Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Defense",
    "Title Re-Defense Planning",
    "Revise Based on the Title Defense Feedback.",
    "Panel-Requested Enhancements Presentation",
    "Team Request for Advisership",
    "Re-Defense: Title Gathering",
    "Re-Defense: Refining the Selected Title",
    "Feedback Gathering",
    "Prepare: Title Re-Defense PowerPoint Presentation",
    "Title Re-Defense: Mock Defense",
    "Title Re-Defense Presentation",
    "Revise Based on the Title Re-Defense Feedback.",
    "Team Request for Advisership",
  ],
  "Extreme Programming": [
    "Brainstorming",
    "Data Gathering: Internet Research",
    "Draft Project Objectives",
    "Title Proposal: Concepts and Layouts",
    "Collect User/ Client Requirements",
    "Title Proposal: Selection of Three Titles",
    "Refining Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Defense",
    "Title Re-Defense Planning",
    "Revise based on the panel feedback.",
    "Panel-Requested Enhancements Presentation",
    "Team Request for Advisership",
    "Re-Defense: Title Gathering",
    "Re-Defense: Refining the Selected Title",
    "Prepare: Title Re-Defense PowerPoint Presentation",
    "Title Re-Defense: Mock Defense",
    "Title Re-Defense Presentation",
    "Revise Based on the Title Re-Defense Feedback.",
    "Team Request for Advisership",
  ],
  RAD: [
    "Brainstorming",
    "Data Gathering: Internet Research",
    "Conduct Initial User Requirements Session",
    "Collect User/Client Requirements",
    "Title Proposal: Concepts and Layouts",
    "Validate Requirements with User/Client",
    "Title Proposal: Selection of Three Titles",
    "Refining Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Defense",
    "Title Re-Defense Planning",
    "Revise Based on the Title Defense Feedback.",
    "Panel-Requested Enhancements Presentation",
    "Team Request for Advisership",
    "Re-Defense: Title Gathering",
    "Re-Defense: Refining the Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Re-Defense Presentation",
    "Revise Based on the Title Re-Defense Feedback.",
    "Team Request for Advisership",
  ],
  Prototyping: [
    "Brainstorming",
    "Data Gathering: Internet Research",
    "Title Proposal: Concepts and Layouts",
    "Interview User/Client",
    "Collect User/Client Requirements",
    "Analyze User/Client Requirements",
    "Title Proposal: Selection of Three Titles",
    "Refining Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Defense",
    "Title Re-Defense Planning",
    "Revise Based on the Title Defense Feedback.",
    "Panel-Requested Enhancements Presentation",
    "Team Request for Advisership",
    "Re-Defense: Title Gathering",
    "Re-Defense: Refining the Selected Title",
    "Requirements Gathering",
    "Prepare: Title Re-Defense PowerPoint Presentation",
    "Title Re-Defense: Mock Defense",
    "Title Re-Defense Presentation",
    "Revise Based on the Title Re-Defense Feedback.",
    "Team Request for Advisership",
  ],
  Spiral: [
    "Brainstorming",
    "Data Gathering: Internet Research",
    "Initial Risk Identification and Analysis",
    "Title Proposal: Concepts and Layouts",
    "Interview User/Client",
    "Collect User/Client Requirements",
    "Title Proposal: Selection of Three Titles",
    "Refining Selected Title",
    "Prepare: PowerPoint Presentation",
    "Title Defense: Mock Defense",
    "Title Defense",
    "Title Re-Defense Planning",
    "Revise Based on the Title Defense Feedback.",
    "Panel-Requested Enhancements Presentation",
    "Team Request for Advisership",
    "Re-Defense: Title Gathering",
    "Re-Defense: Refining the Selected Title",
    "Feedback Gathering",
    "Prepare: Title Re-Defense PowerPoint Presentation",
    "Title Re-Defense: Mock Defense",
    "Title Re-Defense Presentation",
    "Revise Based on the Title Re-Defense Feedback.",
    "Team Request for Advisership",
  ],
};

// ================== Discussion & Review ==================
export const discussionTasks = {
  default: ["Capstone Meeting", "Interview Client"],
  Spiral: ["Capstone Meeting"], // Spiral walang Interview Client
};
