export const finalDefenseTasks = [
    // =========================================================================
    // I. AGILE TASKS
    // =========================================================================
 
    // --- DOCUMENTATION TASKS (Agile Develop Phase) ---
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Revised Manuscript Submission",
        subtask: null,
        elements: null,
    },
    // Polish: Chapter 1
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Project Context",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Background of the Study",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Policies and Procedures",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Users Position",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Objectives",
        elements: "General Objectives",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Objectives",
        elements: "Specific Objectives",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Scope and Limitation",
        elements: "Scope",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Scope and Limitation",
        elements: "Limitation",
    },
    // Polish: Chapter 2
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 2",
        subtask: "Related Theories",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 2",
        subtask: "Related Literature",
        elements: null,
    },
    // Polish: Chapter 3
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Hardware",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Software",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Peopleware",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Hardware",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Software",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Peopleware",
        elements: null,
    },
    // Polish: Chapter 4
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Methodology",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Locale",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Population of the Study",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Organizational Chart/Profile",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Operational Feasibility",
        elements: "Fishbone Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Operational Feasibility",
        elements: "Functional Decomposition Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Technical Feasibility",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Schedule Feasibility",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Economic Feasibility",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Context Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Data Flow Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "System Flowchart",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Program Flowchart",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Use Case Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Use Class Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Sequence Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Activity Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Risk Assessment/Analysis",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Design: Output and User-interface Design Forms",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Design: Data Design",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Model",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Topology",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Security",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Development: Software",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Hardware Specification",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Program Specification",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Programming Environment",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Development Diagram",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Test Plan",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Unit Testing",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Integration Testing",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "System Testing",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Acceptance Testing",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Physical Environment",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Interfaces",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Functionality",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Data",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Security",
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Installation Process",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 5",
        subtask: "Conclusions",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 5",
        subtask: "Recommendations",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 5",
        subtask: "References",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 5",
        subtask: "Resource Person",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Polish: Chapter 5",
        subtask: "Appendices",
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Final Manuscript Review (Post-Defense)",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "Documentation",
        task: "Manuscript Submission for AI and Plagiarism Check",
        subtask: null,
        elements: null,
    },
 
    // --- SYSTEM DEVELOPMENT TASKS (Agile Develop Phase) ---
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "System Development",
        task: "Interface and Feature Consistency Review",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Develop",
        task_type: "System Development",
        task: "Ongoing Bug Resolution and Issue Log Update",
        subtask: null,
        elements: null,
    },
 
    // --- SYSTEM DEVELOPMENT TASKS (Agile Implement Product & Maintain Phase) ---
    {
        methodology: "Agile",
        project_phase: "Implement Product & Maintain",
        task_type: "System Development",
        task: "Final System Deployment to Live Environment",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Implement Product & Maintain",
        task_type: "System Development",
        task: "Adviser Review of Final Deployed System",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Implement Product & Maintain",
        task_type: "Documentation",
        task: "Submit Revised Documentataion Based on Final Defense Feedback",
        subtask: null,
        elements: null,
    },
 
    // --- SYSTEM DEVELOPMENT TASKS (Agile Discussion & Review Phase) ---
    {
        methodology: "Agile",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Milestone Review Meeting",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Agile",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Adviser Follow-Up and Continuous Improvement Plan",
        subtask: null,
        elements: null,
    },
 
    // =========================================================================
    // II. SPIRAL TASKS
    // =========================================================================
 
    // --- SPIRAL Phase: Plan (System Development) ---
    {
        methodology: "Spiral",
        project_phase: "Plan",
        task_type: "System Development",
        task: "Conduct Final Defense",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Spiral",
        project_phase: "Plan",
        task_type: "System Development",
        task: "Review and Incorporate Panel Feedback",
        subtask: null,
        elements: null,
    },
 
    // --- SPIRAL Phase: Determine Objectives (System Development) ---
    {
        methodology: "Spiral",
        project_phase: "Determine Objectives",
        task_type: "System Development",
        task: "Validate Bug Resolution and System Stability",
        subtask: null,
        elements: null,
    },
 
    // --- SPIRAL Phase: Develop & Test (System Development) ---
    {
        methodology: "Spiral",
        project_phase: "Develop & Test",
        task_type: "System Development",
        task: "Perform Final Regression Testing",
        subtask: null,
        elements: null,
    },
 
    // --- SPIRAL Phase: Develop & Test (Documentation) ---
    {
        methodology: "Spiral",
        project_phase: "Develop & Test",
        task_type: "Documentation",
        task: "Generate Final Defense Video/Presentation Material",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Spiral",
        project_phase: "Develop & Test",
        task_type: "Documentation",
        task: "Final Review of System Manuals (User, Technical)",
        subtask: null,
        elements: null,
    },
 
    // --- SPIRAL Phase: Assess Alternatives (System Development) ---
    {
        methodology: "Spiral",
        project_phase: "Assess Alternatives",
        task_type: "System Development",
        task: "Facilitate Panel Re-evaluation (if necessary)",
        subtask: null,
        elements: null,
    },
 
    // =========================================================================
    // III. EXTREME PROGRAMMING (XP) TASKS
    // =========================================================================
 
    // --- XP Phase: Release (System Development) ---
    {
        methodology: "Extreme Programming (XP)",
        project_phase: "Release",
        task_type: "System Development",
        task: "System Demo and Walkthrough to Adviser/Panel",
        subtask: null,
        elements: null,
    },
 
    // --- XP Phase: Release (Documentation) ---
    {
        methodology: "Extreme Programming (XP)",
        project_phase: "Release",
        task_type: "Documentation",
        task: "Final Document Compilation and Binding Preparation",
        subtask: null,
        elements: null,
    },
 
    // --- XP Phase: Planning (System Development) ---
    {
        methodology: "Extreme Programming (XP)",
        project_phase: "Planning",
        task_type: "System Development",
        task: "User Stories and Acceptance Test Final Review",
        subtask: null,
        elements: null,
    },
 
    // --- XP Phase: Iterations (System Development) ---
    {
        methodology: "Extreme Programming (XP)",
        project_phase: "Iterations",
        task_type: "System Development",
        task: "Refactoring and Code Cleanup (Post-Defense Fixes)",
        subtask: null,
        elements: null,
    },
 
    // =========================================================================
    // IV. RAPID APPLICATION DEVELOPMENT (RAD) TASKS
    // =========================================================================
 
    // --- RAD Phase: Cutover (System Development) ---
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Cutover",
        task_type: "System Development",
        task: "Facilitate Bug Resolution Confirmation",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Cutover",
        task_type: "System Development",
        task: "Final System Deployment",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Cutover",
        task_type: "System Development",
        task: "Adviser Review of Deployed System",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Cutover",
        task_type: "Documentation",
        task: "Submit Revised Documentataion Based on Final Defense Feedback",
        subtask: null,
        elements: null,
    },
 
    // --- RAD Phase: Discussion & Review (System Development) ---
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Milestone Review Meeting",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Rapid Application Development (RAD)",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Adviser Follow-Up and Continuous Improvement Plan",
        subtask: null,
        elements: null,
    },
 
    // =========================================================================
    // V. PROTOTYPING TASKS (FROM Caps-Prototyping-Tasks.docx)
    // =========================================================================
 
    // --- Prototyping Phase: Refining Prototyping (Documentation) ---
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Update UI/UX Based on Feedback", // Note: This is documentation of the design, not system development.
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Revised Manuscript Submission",
        subtask: null,
        elements: null,
    },
    // Polish: Chapter 1
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Project Context",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Background of the Study",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Policies and Procedures",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Introduction",
        elements: "Users Position",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Objectives",
        elements: "General Objectives",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Objectives",
        elements: "Specific Objectives",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Scope and Limitation",
        elements: "Scope",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 1",
        subtask: "Scope and Limitation",
        elements: "Limitation",
    },
    // Polish: Chapter 2
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 2",
        subtask: "Related Theories",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 2",
        subtask: "Related Literature",
        elements: null,
    },
    // Polish: Chapter 3
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Hardware",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Software",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Implementation: Peopleware",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Hardware",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Software",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 3",
        subtask: "Development: Peopleware",
        elements: null,
    },
    // Polish: Chapter 4
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Methodology",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Locale",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Population of the Study",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Environment: Organizational Chart/Profile",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Operational Feasibility",
        elements: "Fishbone Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Operational Feasibility",
        elements: "Functional Decomposition Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Technical Feasibility",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Schedule Feasibility",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Feasibility",
        elements: "Economic Feasibility",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Context Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Data Flow Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "System Flowchart",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Program Flowchart",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Use Case Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Use Class Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Sequence Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Requirements Modeling",
        elements: "Activity Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Requirement Specification: Risk Assessment/Analysis",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Design: Output and User-interface Design Forms",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Design: Data Design",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Model",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Topology",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "System Architecture: Network Security",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Development: Software",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Hardware Specification",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Program Specification",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Programming Environment",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Development Diagram",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Prepare: Remaining Sections of Chapter 4",
        elements: "Test Plan",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Unit Testing",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Integration Testing",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "System Testing",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Verification and Testing",
        elements: "Acceptance Testing",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Physical Environment",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Interfaces",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Functionality",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Data",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Implementation Plan",
        elements: "Security",
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Polish: Chapter 4",
        subtask: "Installation Process",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Complete: Chapter 5",
        subtask: "Conclusions",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Complete: Chapter 5",
        subtask: "Recommendations",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Complete: Chapter 5",
        subtask: "References",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Complete: Chapter 5",
        subtask: "Resource Person",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Complete: Chapter 5",
        subtask: "Appendices",
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Final Manuscript Review (Post-Defense)",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "Documentation",
        task: "Manuscript Submission for AI and Plagiarism Check",
        subtask: null,
        elements: null,
    },
 
    // --- Prototyping Phase: Refining Prototyping (System Development) ---
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "System Development",
        task: "Interface and Feature Consistency Review",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Refining Prototyping",
        task_type: "System Development",
        task: "Ongoing Bug Resolution and Issue Log Update",
        subtask: null,
        elements: null,
    },
 
    // --- Prototyping Phase: Implement Product & Maintain (System Development) ---
    {
        methodology: "Prototyping",
        project_phase: "Implement Product & Maintain",
        task_type: "System Development",
        task: "Final System Deployment to Live Environment",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Implement Product & Maintain",
        task_type: "System Development",
        task: "Adviser Review of Final Deployed System",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Implement Product & Maintain",
        task_type: "Documentation",
        task: "Submit Revised Documentataion Based on Final Defense Feedback",
        subtask: null,
        elements: null,
    },
 
    // --- Prototyping Phase: Discussion & Review (System Development) ---
    {
        methodology: "Prototyping",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Milestone Review Meeting",
        subtask: null,
        elements: null,
    },
    {
        methodology: "Prototyping",
        project_phase: "Discussion & Review",
        task_type: "System Development",
        task: "Adviser Follow-Up and Continuous Improvement Plan",
        subtask: null,
        elements: null,
    },
];